/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDUMMY_MODULE_H
#define _MOCKDUMMY_MODULE_H

#include "unity.h"
#include "dummy_module.h"
#include "CException.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockdummy_module_Init(void);
void Mockdummy_module_Destroy(void);
void Mockdummy_module_Verify(void);




#define dummy_module__get_zero_IgnoreAndReturn(cmock_retval) dummy_module__get_zero_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dummy_module__get_zero_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, size_t cmock_to_return);
#define dummy_module__get_zero_ExpectAndReturn(cmock_retval) dummy_module__get_zero_CMockExpectAndReturn(__LINE__, cmock_retval)
void dummy_module__get_zero_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t cmock_to_return);
typedef size_t (* CMOCK_dummy_module__get_zero_CALLBACK)(int cmock_num_calls);
void dummy_module__get_zero_AddCallback(CMOCK_dummy_module__get_zero_CALLBACK Callback);
void dummy_module__get_zero_Stub(CMOCK_dummy_module__get_zero_CALLBACK Callback);
#define dummy_module__get_zero_StubWithCallback dummy_module__get_zero_Stub
#define dummy_module__get_zero_ExpectAndThrow(cmock_to_throw) dummy_module__get_zero_CMockExpectAndThrow(__LINE__, cmock_to_throw)
void dummy_module__get_zero_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
