/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockdummy_module.h"

static const char* CMockString_dummy_module__get_zero = "dummy_module__get_zero";

typedef struct _CMOCK_dummy_module__get_zero_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  size_t ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_dummy_module__get_zero_CALL_INSTANCE;

static struct Mockdummy_moduleInstance
{
  int dummy_module__get_zero_IgnoreBool;
  size_t dummy_module__get_zero_FinalReturn;
  int dummy_module__get_zero_CallbackBool;
  CMOCK_dummy_module__get_zero_CALLBACK dummy_module__get_zero_CallbackFunctionPointer;
  int dummy_module__get_zero_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dummy_module__get_zero_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockdummy_module_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.dummy_module__get_zero_CallInstance;
  if (Mock.dummy_module__get_zero_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dummy_module__get_zero);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.dummy_module__get_zero_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
}

void Mockdummy_module_Init(void)
{
  Mockdummy_module_Destroy();
}

void Mockdummy_module_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

size_t dummy_module__get_zero(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dummy_module__get_zero_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dummy_module__get_zero);
  cmock_call_instance = (CMOCK_dummy_module__get_zero_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dummy_module__get_zero_CallInstance);
  Mock.dummy_module__get_zero_CallInstance = CMock_Guts_MemNext(Mock.dummy_module__get_zero_CallInstance);
  if (Mock.dummy_module__get_zero_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dummy_module__get_zero_FinalReturn;
    memcpy((void*)(&Mock.dummy_module__get_zero_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(size_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dummy_module__get_zero_CallbackBool &&
      Mock.dummy_module__get_zero_CallbackFunctionPointer != NULL)
  {
    size_t ret = Mock.dummy_module__get_zero_CallbackFunctionPointer(Mock.dummy_module__get_zero_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dummy_module__get_zero_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.dummy_module__get_zero_CallbackFunctionPointer(Mock.dummy_module__get_zero_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dummy_module__get_zero_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, size_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dummy_module__get_zero_CALL_INSTANCE));
  CMOCK_dummy_module__get_zero_CALL_INSTANCE* cmock_call_instance = (CMOCK_dummy_module__get_zero_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dummy_module__get_zero_CallInstance = CMock_Guts_MemChain(Mock.dummy_module__get_zero_CallInstance, cmock_guts_index);
  Mock.dummy_module__get_zero_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dummy_module__get_zero_IgnoreBool = (int)1;
}

void dummy_module__get_zero_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dummy_module__get_zero_CALL_INSTANCE));
  CMOCK_dummy_module__get_zero_CALL_INSTANCE* cmock_call_instance = (CMOCK_dummy_module__get_zero_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dummy_module__get_zero_CallInstance = CMock_Guts_MemChain(Mock.dummy_module__get_zero_CallInstance, cmock_guts_index);
  Mock.dummy_module__get_zero_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(size_t[sizeof(cmock_to_return) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void dummy_module__get_zero_AddCallback(CMOCK_dummy_module__get_zero_CALLBACK Callback)
{
  Mock.dummy_module__get_zero_IgnoreBool = (int)0;
  Mock.dummy_module__get_zero_CallbackBool = (int)1;
  Mock.dummy_module__get_zero_CallbackFunctionPointer = Callback;
}

void dummy_module__get_zero_Stub(CMOCK_dummy_module__get_zero_CALLBACK Callback)
{
  Mock.dummy_module__get_zero_IgnoreBool = (int)0;
  Mock.dummy_module__get_zero_CallbackBool = (int)0;
  Mock.dummy_module__get_zero_CallbackFunctionPointer = Callback;
}

void dummy_module__get_zero_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dummy_module__get_zero_CALL_INSTANCE));
  CMOCK_dummy_module__get_zero_CALL_INSTANCE* cmock_call_instance = (CMOCK_dummy_module__get_zero_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dummy_module__get_zero_CallInstance = CMock_Guts_MemChain(Mock.dummy_module__get_zero_CallInstance, cmock_guts_index);
  Mock.dummy_module__get_zero_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

