/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdio.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_sl_string__initialize_successful(void);
extern void test_sl_string__initialize_unsuccessful_null_mem(void);
extern void test_sl_string__initialize_unsuccessful_mem_size_zero(void);
extern void test_sl_string__initialize_from_successful(void);
extern void test_sl_string__initialize_from_null_init_string(void);
extern void test_sl_string__initialize_from_null_string_memory(void);
extern void test_sl_string__get_capacity(void);
extern void test_sl_string__is_full(void);
extern void test_sl_string__get_length_empty_string(void);
extern void test_sl_string__get_length_non_empty_string(void);
extern void test_sl_string__c_str_empty_string(void);
extern void test_sl_string__c_str_non_empty_string(void);
extern void test_append_char(void);
extern void test_sl_string__copy_to(void);
extern void test_sl_string__to_int_successful(void);
extern void test_sl_string__to_int_unsuccessful_contains_non_int_chars(void);
extern void test_sl_string__to_int_unsuccessful_empty_string(void);
extern void test_sl_string__to_float_successful(void);
extern void test_sl_string__to_float_unsuccessful_contains_non_float_chars(void);
extern void test_sl_string__to_float_unsuccessful_empty_string(void);
extern void test_sl_string__is_alpha_contains_only_alpha_chars(void);
extern void test_sl_string__is_alpha_contains_non_alpha_chars(void);
extern void test_sl_string__is_alpha_empty_string(void);
extern void test_sl_string__is_alphanum_successful(void);
extern void test_sl_string__is_alphanum_contains_non_alphanum_chars(void);
extern void test_sl_string__is_alphanum_empty_string(void);
extern void test_sl_string__clear(void);
extern void test_sl_string__clear_all_memory(void);
extern void test_sl_string__to_lower(void);
extern void test_sl_string__to_upper(void);
extern void test_sl_string__printf_successful(void);
extern void test_sl_string__printf_with_string_size_zero(void);
extern void test_sl_string__printf_append_with_string_size_zero(void);
extern void test_sl_string__printf_filename_format(void);
extern void test_sl_string__scanf_with_arg_size_zero(void);
extern void test_sl_string__printf_truncated(void);
extern void test_sl_string__printf_append_successful(void);
extern void test_sl_string__printf_append_truncated(void);
extern void test_sl_string__scanf_successful(void);
extern void test_sl_string__tokenize_successful(void);
extern void test_sl_string__tokenize_unsuccessful_null_delimiter(void);
extern void test_sl_string__tokenize_null_args(void);
extern void test_sl_string__tokenize_mismatch_of_ptrs_and_num_of_tokens(void);
extern void test_sl_string__set(void);
extern void test_sl_string__insert_at_success(void);
extern void test_sl_string__insert_at_pos_out_of_bounds(void);
extern void test_sl_string__insert_at_string_is_null(void);
extern void test_sl_string__insert_at_capacity_reached(void);
extern void test_sl_string__append_successful(void);
extern void test_sl_string__append_string_is_null(void);
extern void test_sl_string__append_capacity_reached(void);
extern void test_sl_string__equals_to_successful(void);
extern void test_sl_string__equals_to_unsuccessful_strings_dont_match(void);
extern void test_sl_string__equals_to_unsuccessful_null_substring(void);
extern void test_sl_string__equals_to_ignore_case_successful(void);
extern void test_sl_string__equals_to_ignore_case_unsuccessful_strings_dont_match(void);
extern void test_sl_string__equals_to_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__last_index_of_found(void);
extern void test_sl_string__last_index_of_unsuccessful_not_found(void);
extern void test_sl_string__last_index_of_unsuccessful_null_substring(void);
extern void test_sl_string__last_index_of_ignore_case_found(void);
extern void test_sl_string_last_index_of_ignore_lower_case(void);
extern void test_sl_string_last_index_of_ignore_multiple_sub_string(void);
extern void test_sl_string__last_index_of_ignore_case_not_found(void);
extern void test_sl_string__last_index_of_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__first_index_of_found(void);
extern void test_sl_string__first_index_of_unsuccessful_not_found(void);
extern void test_sl_string__first_index_of_unsuccessful_null_substring(void);
extern void test_sl_string__first_index_of_ignore_case_found(void);
extern void test_sl_string__first_index_of_ignore_case_not_found(void);
extern void test_sl_string__first_index_of_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string_first_index_of_ignore_lower_case(void);
extern void test_sl_string__contains_found(void);
extern void test_sl_string__contains_unsuccessful_not_found(void);
extern void test_sl_string__contains_unsuccessful_null_substring(void);
extern void test_sl_string__contains_ignore_case_found(void);
extern void test_sl_string__contains_ignore_case_not_found(void);
extern void test_sl_string__contains_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__count_of_successful(void);
extern void test_sl_string__count_of_no_occurance(void);
extern void test_sl_string__count_of_unsuccessful_null_substring(void);
extern void test_sl_string__begins_with_found(void);
extern void test_sl_string__begins_with_unsuccessful_not_found(void);
extern void test_sl_string__begins_with_unsuccessful_null_substring(void);
extern void test_sl_string__begins_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_limited_chars(void);
extern void test_sl_string__begins_with_ignore_case_found(void);
extern void test_sl_string__begins_with_ignore_case_not_found(void);
extern void test_sl_string__begins_with_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__begins_ignore_case_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_whole_word_found(void);
extern void test_sl_string__begins_with_whole_word_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_whole_word_not_matching(void);
extern void test_sl_string__begins_with_whole_word_string_ends_with_null(void);
extern void test_sl_string__begins_with_whole_word_unsuccessful_not_found(void);
extern void test_sl_string__begins_with_whole_word_unsuccessful_null_params(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_found(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_not_found(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_null_params(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_large_substring(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_not_matching(void);
extern void test_sl_string__begins_with_whole_word_ignore_case_string_delimeter_null(void);
extern void test_sl_string__ends_with_found(void);
extern void test_sl_string__ends_with_unsuccessful_large_substring(void);
extern void test_sl_string__ends_with_unsuccessful_not_found(void);
extern void test_sl_string__ends_with_unsuccessful_null_substring(void);
extern void test_sl_string__ends_newline(void);
extern void test_sl_string__ends_with_ignore_case_found(void);
extern void test_sl_string__ends_with_ignore_case_unsuccessful_large_substring(void);
extern void test_sl_string__ends_with_ignore_case_not_found(void);
extern void test_sl_string__ends_with_ignore_case_unsuccessful_null_substring(void);
extern void test_sl_string__erase_successful(void);
extern void test_sl_string__erase_null_substring(void);
extern void test_sl_string__erase_substring_not_found(void);
extern void test_sl_string__erase_first_successful(void);
extern void test_sl_string__erase_first_n_chars_longer_than_string(void);
extern void test_sl_string__erase_last_successful(void);
extern void test_sl_string__erase_last_n_chars_longer_than_string(void);
extern void test_sl_string__erase_at_successful(void);
extern void test_sl_string__erase_at_index_out_of_bounds(void);
extern void test_sl_string__erase_after_successful(void);
extern void test_sl_string__erase_after_index_out_of_bounds(void);
extern void test_sl_string__erase_after_n_chars_longer_than_string(void);
extern void test_sl_string__erase_after_string(void);
extern void test_sl_string__erase_first_word_successful(void);
extern void test_sl_string__erase_first_word_no_words(void);
extern void test_sl_string__erase_special_chars_successful(void);
extern void test_sl_string__erase_special_chars_no_special_chars(void);
extern void test_erase_int(void);
extern void test_sl_string__trim_end_successful(void);
extern void test_sl_string__trim_end_null_chars_to_trim(void);
extern void test_sl_string__trim_end_chars_not_found(void);
extern void test_sl_string__trim_start_successful(void);
extern void test_sl_string__trim_start_null_chars_to_trim(void);
extern void test_sl_string__trim_start_chars_not_found(void);
extern void test_sl_string__replace_first_successful(void);
extern void test_sl_string__replace_first_null_params(void);
extern void test_sl_string__replace_first_substring_not_found(void);
extern void test_sl_string__replace_first_empty_string_and_replace_string(void);
extern void test_sl_string__replace_last_successful(void);
extern void test_sl_string__replace_last_null_params(void);
extern void test_sl_string__replace_last_substring_not_found(void);
extern void test_sl_string__replace_all_successful(void);
extern void test_sl_string__replace_all_null_params(void);
extern void test_sl_string__replace_all_substring_not_found(void);
extern void test_sl_string__replace_all_double_slash_with_slash(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("projects/lpc40xx_freertos/l2_utils/string/test/test_sl_string.c");
  run_test(test_sl_string__initialize_successful, "test_sl_string__initialize_successful", 87);
  run_test(test_sl_string__initialize_unsuccessful_null_mem, "test_sl_string__initialize_unsuccessful_null_mem", 93);
  run_test(test_sl_string__initialize_unsuccessful_mem_size_zero, "test_sl_string__initialize_unsuccessful_mem_size_zero", 100);
  run_test(test_sl_string__initialize_from_successful, "test_sl_string__initialize_from_successful", 106);
  run_test(test_sl_string__initialize_from_null_init_string, "test_sl_string__initialize_from_null_init_string", 117);
  run_test(test_sl_string__initialize_from_null_string_memory, "test_sl_string__initialize_from_null_string_memory", 127);
  run_test(test_sl_string__get_capacity, "test_sl_string__get_capacity", 134);
  run_test(test_sl_string__is_full, "test_sl_string__is_full", 140);
  run_test(test_sl_string__get_length_empty_string, "test_sl_string__get_length_empty_string", 151);
  run_test(test_sl_string__get_length_non_empty_string, "test_sl_string__get_length_non_empty_string", 155);
  run_test(test_sl_string__c_str_empty_string, "test_sl_string__c_str_empty_string", 162);
  run_test(test_sl_string__c_str_non_empty_string, "test_sl_string__c_str_non_empty_string", 167);
  run_test(test_append_char, "test_append_char", 175);
  run_test(test_sl_string__copy_to, "test_sl_string__copy_to", 199);
  run_test(test_sl_string__to_int_successful, "test_sl_string__to_int_successful", 228);
  run_test(test_sl_string__to_int_unsuccessful_contains_non_int_chars, "test_sl_string__to_int_unsuccessful_contains_non_int_chars", 238);
  run_test(test_sl_string__to_int_unsuccessful_empty_string, "test_sl_string__to_int_unsuccessful_empty_string", 252);
  run_test(test_sl_string__to_float_successful, "test_sl_string__to_float_successful", 256);
  run_test(test_sl_string__to_float_unsuccessful_contains_non_float_chars, "test_sl_string__to_float_unsuccessful_contains_non_float_chars", 270);
  run_test(test_sl_string__to_float_unsuccessful_empty_string, "test_sl_string__to_float_unsuccessful_empty_string", 284);
  run_test(test_sl_string__is_alpha_contains_only_alpha_chars, "test_sl_string__is_alpha_contains_only_alpha_chars", 288);
  run_test(test_sl_string__is_alpha_contains_non_alpha_chars, "test_sl_string__is_alpha_contains_non_alpha_chars", 293);
  run_test(test_sl_string__is_alpha_empty_string, "test_sl_string__is_alpha_empty_string", 298);
  run_test(test_sl_string__is_alphanum_successful, "test_sl_string__is_alphanum_successful", 302);
  run_test(test_sl_string__is_alphanum_contains_non_alphanum_chars, "test_sl_string__is_alphanum_contains_non_alphanum_chars", 316);
  run_test(test_sl_string__is_alphanum_empty_string, "test_sl_string__is_alphanum_empty_string", 322);
  run_test(test_sl_string__clear, "test_sl_string__clear", 326);
  run_test(test_sl_string__clear_all_memory, "test_sl_string__clear_all_memory", 334);
  run_test(test_sl_string__to_lower, "test_sl_string__to_lower", 347);
  run_test(test_sl_string__to_upper, "test_sl_string__to_upper", 353);
  run_test(test_sl_string__printf_successful, "test_sl_string__printf_successful", 359);
  run_test(test_sl_string__printf_with_string_size_zero, "test_sl_string__printf_with_string_size_zero", 368);
  run_test(test_sl_string__printf_append_with_string_size_zero, "test_sl_string__printf_append_with_string_size_zero", 375);
  run_test(test_sl_string__printf_filename_format, "test_sl_string__printf_filename_format", 382);
  run_test(test_sl_string__scanf_with_arg_size_zero, "test_sl_string__scanf_with_arg_size_zero", 395);
  run_test(test_sl_string__printf_truncated, "test_sl_string__printf_truncated", 403);
  run_test(test_sl_string__printf_append_successful, "test_sl_string__printf_append_successful", 419);
  run_test(test_sl_string__printf_append_truncated, "test_sl_string__printf_append_truncated", 430);
  run_test(test_sl_string__scanf_successful, "test_sl_string__scanf_successful", 453);
  run_test(test_sl_string__tokenize_successful, "test_sl_string__tokenize_successful", 468);
  run_test(test_sl_string__tokenize_unsuccessful_null_delimiter, "test_sl_string__tokenize_unsuccessful_null_delimiter", 483);
  run_test(test_sl_string__tokenize_null_args, "test_sl_string__tokenize_null_args", 498);
  run_test(test_sl_string__tokenize_mismatch_of_ptrs_and_num_of_tokens, "test_sl_string__tokenize_mismatch_of_ptrs_and_num_of_tokens", 503);
  run_test(test_sl_string__set, "test_sl_string__set", 517);
  run_test(test_sl_string__insert_at_success, "test_sl_string__insert_at_success", 533);
  run_test(test_sl_string__insert_at_pos_out_of_bounds, "test_sl_string__insert_at_pos_out_of_bounds", 539);
  run_test(test_sl_string__insert_at_string_is_null, "test_sl_string__insert_at_string_is_null", 546);
  run_test(test_sl_string__insert_at_capacity_reached, "test_sl_string__insert_at_capacity_reached", 552);
  run_test(test_sl_string__append_successful, "test_sl_string__append_successful", 558);
  run_test(test_sl_string__append_string_is_null, "test_sl_string__append_string_is_null", 564);
  run_test(test_sl_string__append_capacity_reached, "test_sl_string__append_capacity_reached", 570);
  run_test(test_sl_string__equals_to_successful, "test_sl_string__equals_to_successful", 576);
  run_test(test_sl_string__equals_to_unsuccessful_strings_dont_match, "test_sl_string__equals_to_unsuccessful_strings_dont_match", 581);
  run_test(test_sl_string__equals_to_unsuccessful_null_substring, "test_sl_string__equals_to_unsuccessful_null_substring", 586);
  run_test(test_sl_string__equals_to_ignore_case_successful, "test_sl_string__equals_to_ignore_case_successful", 591);
  run_test(test_sl_string__equals_to_ignore_case_unsuccessful_strings_dont_match, "test_sl_string__equals_to_ignore_case_unsuccessful_strings_dont_match", 597);
  run_test(test_sl_string__equals_to_ignore_case_unsuccessful_null_substring, "test_sl_string__equals_to_ignore_case_unsuccessful_null_substring", 603);
  run_test(test_sl_string__last_index_of_found, "test_sl_string__last_index_of_found", 608);
  run_test(test_sl_string__last_index_of_unsuccessful_not_found, "test_sl_string__last_index_of_unsuccessful_not_found", 613);
  run_test(test_sl_string__last_index_of_unsuccessful_null_substring, "test_sl_string__last_index_of_unsuccessful_null_substring", 618);
  run_test(test_sl_string__last_index_of_ignore_case_found, "test_sl_string__last_index_of_ignore_case_found", 623);
  run_test(test_sl_string_last_index_of_ignore_lower_case, "test_sl_string_last_index_of_ignore_lower_case", 633);
  run_test(test_sl_string_last_index_of_ignore_multiple_sub_string, "test_sl_string_last_index_of_ignore_multiple_sub_string", 638);
  run_test(test_sl_string__last_index_of_ignore_case_not_found, "test_sl_string__last_index_of_ignore_case_not_found", 643);
  run_test(test_sl_string__last_index_of_ignore_case_unsuccessful_null_substring, "test_sl_string__last_index_of_ignore_case_unsuccessful_null_substring", 647);
  run_test(test_sl_string__first_index_of_found, "test_sl_string__first_index_of_found", 653);
  run_test(test_sl_string__first_index_of_unsuccessful_not_found, "test_sl_string__first_index_of_unsuccessful_not_found", 663);
  run_test(test_sl_string__first_index_of_unsuccessful_null_substring, "test_sl_string__first_index_of_unsuccessful_null_substring", 668);
  run_test(test_sl_string__first_index_of_ignore_case_found, "test_sl_string__first_index_of_ignore_case_found", 673);
  run_test(test_sl_string__first_index_of_ignore_case_not_found, "test_sl_string__first_index_of_ignore_case_not_found", 683);
  run_test(test_sl_string__first_index_of_ignore_case_unsuccessful_null_substring, "test_sl_string__first_index_of_ignore_case_unsuccessful_null_substring", 688);
  run_test(test_sl_string_first_index_of_ignore_lower_case, "test_sl_string_first_index_of_ignore_lower_case", 694);
  run_test(test_sl_string__contains_found, "test_sl_string__contains_found", 699);
  run_test(test_sl_string__contains_unsuccessful_not_found, "test_sl_string__contains_unsuccessful_not_found", 704);
  run_test(test_sl_string__contains_unsuccessful_null_substring, "test_sl_string__contains_unsuccessful_null_substring", 709);
  run_test(test_sl_string__contains_ignore_case_found, "test_sl_string__contains_ignore_case_found", 714);
  run_test(test_sl_string__contains_ignore_case_not_found, "test_sl_string__contains_ignore_case_not_found", 719);
  run_test(test_sl_string__contains_ignore_case_unsuccessful_null_substring, "test_sl_string__contains_ignore_case_unsuccessful_null_substring", 724);
  run_test(test_sl_string__count_of_successful, "test_sl_string__count_of_successful", 729);
  run_test(test_sl_string__count_of_no_occurance, "test_sl_string__count_of_no_occurance", 734);
  run_test(test_sl_string__count_of_unsuccessful_null_substring, "test_sl_string__count_of_unsuccessful_null_substring", 739);
  run_test(test_sl_string__begins_with_found, "test_sl_string__begins_with_found", 744);
  run_test(test_sl_string__begins_with_unsuccessful_not_found, "test_sl_string__begins_with_unsuccessful_not_found", 749);
  run_test(test_sl_string__begins_with_unsuccessful_null_substring, "test_sl_string__begins_with_unsuccessful_null_substring", 754);
  run_test(test_sl_string__begins_unsuccessful_large_substring, "test_sl_string__begins_unsuccessful_large_substring", 759);
  run_test(test_sl_string__begins_with_limited_chars, "test_sl_string__begins_with_limited_chars", 764);
  run_test(test_sl_string__begins_with_ignore_case_found, "test_sl_string__begins_with_ignore_case_found", 780);
  run_test(test_sl_string__begins_with_ignore_case_not_found, "test_sl_string__begins_with_ignore_case_not_found", 785);
  run_test(test_sl_string__begins_with_ignore_case_unsuccessful_null_substring, "test_sl_string__begins_with_ignore_case_unsuccessful_null_substring", 790);
  run_test(test_sl_string__begins_ignore_case_unsuccessful_large_substring, "test_sl_string__begins_ignore_case_unsuccessful_large_substring", 795);
  run_test(test_sl_string__begins_with_whole_word_found, "test_sl_string__begins_with_whole_word_found", 800);
  run_test(test_sl_string__begins_with_whole_word_unsuccessful_large_substring, "test_sl_string__begins_with_whole_word_unsuccessful_large_substring", 810);
  run_test(test_sl_string__begins_with_whole_word_not_matching, "test_sl_string__begins_with_whole_word_not_matching", 815);
  run_test(test_sl_string__begins_with_whole_word_string_ends_with_null, "test_sl_string__begins_with_whole_word_string_ends_with_null", 820);
  run_test(test_sl_string__begins_with_whole_word_unsuccessful_not_found, "test_sl_string__begins_with_whole_word_unsuccessful_not_found", 825);
  run_test(test_sl_string__begins_with_whole_word_unsuccessful_null_params, "test_sl_string__begins_with_whole_word_unsuccessful_null_params", 830);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_found, "test_sl_string__begins_with_whole_word_ignore_case_found", 837);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_not_found, "test_sl_string__begins_with_whole_word_ignore_case_not_found", 849);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_null_params, "test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_null_params", 855);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_large_substring, "test_sl_string__begins_with_whole_word_ignore_case_unsuccessful_large_substring", 865);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_not_matching, "test_sl_string__begins_with_whole_word_ignore_case_not_matching", 872);
  run_test(test_sl_string__begins_with_whole_word_ignore_case_string_delimeter_null, "test_sl_string__begins_with_whole_word_ignore_case_string_delimeter_null", 878);
  run_test(test_sl_string__ends_with_found, "test_sl_string__ends_with_found", 885);
  run_test(test_sl_string__ends_with_unsuccessful_large_substring, "test_sl_string__ends_with_unsuccessful_large_substring", 890);
  run_test(test_sl_string__ends_with_unsuccessful_not_found, "test_sl_string__ends_with_unsuccessful_not_found", 895);
  run_test(test_sl_string__ends_with_unsuccessful_null_substring, "test_sl_string__ends_with_unsuccessful_null_substring", 900);
  run_test(test_sl_string__ends_newline, "test_sl_string__ends_newline", 905);
  run_test(test_sl_string__ends_with_ignore_case_found, "test_sl_string__ends_with_ignore_case_found", 919);
  run_test(test_sl_string__ends_with_ignore_case_unsuccessful_large_substring, "test_sl_string__ends_with_ignore_case_unsuccessful_large_substring", 925);
  run_test(test_sl_string__ends_with_ignore_case_not_found, "test_sl_string__ends_with_ignore_case_not_found", 931);
  run_test(test_sl_string__ends_with_ignore_case_unsuccessful_null_substring, "test_sl_string__ends_with_ignore_case_unsuccessful_null_substring", 937);
  run_test(test_sl_string__erase_successful, "test_sl_string__erase_successful", 943);
  run_test(test_sl_string__erase_null_substring, "test_sl_string__erase_null_substring", 950);
  run_test(test_sl_string__erase_substring_not_found, "test_sl_string__erase_substring_not_found", 957);
  run_test(test_sl_string__erase_first_successful, "test_sl_string__erase_first_successful", 964);
  run_test(test_sl_string__erase_first_n_chars_longer_than_string, "test_sl_string__erase_first_n_chars_longer_than_string", 971);
  run_test(test_sl_string__erase_last_successful, "test_sl_string__erase_last_successful", 978);
  run_test(test_sl_string__erase_last_n_chars_longer_than_string, "test_sl_string__erase_last_n_chars_longer_than_string", 985);
  run_test(test_sl_string__erase_at_successful, "test_sl_string__erase_at_successful", 992);
  run_test(test_sl_string__erase_at_index_out_of_bounds, "test_sl_string__erase_at_index_out_of_bounds", 999);
  run_test(test_sl_string__erase_after_successful, "test_sl_string__erase_after_successful", 1006);
  run_test(test_sl_string__erase_after_index_out_of_bounds, "test_sl_string__erase_after_index_out_of_bounds", 1013);
  run_test(test_sl_string__erase_after_n_chars_longer_than_string, "test_sl_string__erase_after_n_chars_longer_than_string", 1021);
  run_test(test_sl_string__erase_after_string, "test_sl_string__erase_after_string", 1029);
  run_test(test_sl_string__erase_first_word_successful, "test_sl_string__erase_first_word_successful", 1039);
  run_test(test_sl_string__erase_first_word_no_words, "test_sl_string__erase_first_word_no_words", 1046);
  run_test(test_sl_string__erase_special_chars_successful, "test_sl_string__erase_special_chars_successful", 1053);
  run_test(test_sl_string__erase_special_chars_no_special_chars, "test_sl_string__erase_special_chars_no_special_chars", 1060);
  run_test(test_erase_int, "test_erase_int", 1067);
  run_test(test_sl_string__trim_end_successful, "test_sl_string__trim_end_successful", 1095);
  run_test(test_sl_string__trim_end_null_chars_to_trim, "test_sl_string__trim_end_null_chars_to_trim", 1102);
  run_test(test_sl_string__trim_end_chars_not_found, "test_sl_string__trim_end_chars_not_found", 1109);
  run_test(test_sl_string__trim_start_successful, "test_sl_string__trim_start_successful", 1116);
  run_test(test_sl_string__trim_start_null_chars_to_trim, "test_sl_string__trim_start_null_chars_to_trim", 1126);
  run_test(test_sl_string__trim_start_chars_not_found, "test_sl_string__trim_start_chars_not_found", 1133);
  run_test(test_sl_string__replace_first_successful, "test_sl_string__replace_first_successful", 1140);
  run_test(test_sl_string__replace_first_null_params, "test_sl_string__replace_first_null_params", 1147);
  run_test(test_sl_string__replace_first_substring_not_found, "test_sl_string__replace_first_substring_not_found", 1157);
  run_test(test_sl_string__replace_first_empty_string_and_replace_string, "test_sl_string__replace_first_empty_string_and_replace_string", 1164);
  run_test(test_sl_string__replace_last_successful, "test_sl_string__replace_last_successful", 1170);
  run_test(test_sl_string__replace_last_null_params, "test_sl_string__replace_last_null_params", 1177);
  run_test(test_sl_string__replace_last_substring_not_found, "test_sl_string__replace_last_substring_not_found", 1187);
  run_test(test_sl_string__replace_all_successful, "test_sl_string__replace_all_successful", 1194);
  run_test(test_sl_string__replace_all_null_params, "test_sl_string__replace_all_null_params", 1201);
  run_test(test_sl_string__replace_all_substring_not_found, "test_sl_string__replace_all_substring_not_found", 1211);
  run_test(test_sl_string__replace_all_double_slash_with_slash, "test_sl_string__replace_all_double_slash_with_slash", 1218);

  return UnityEnd();
}
